<?php 
/*
Plugin Name: Aspire Responsive Menu
Plugin URI: https://aspireitsolution.com
Description: This plugin is used only for responsive menu in website.
Version: 0.0.1
Author: Priti Panwar
Author URI: https://aspireitsolution.com
Text Domain: arm
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}